# Generated by Django 6.0.6 on 2026-07-03 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('homes', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='device',
            name='room',
        ),
        migrations.RemoveField(
            model_name='devicecapability',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='device',
        ),
        migrations.CreateModel(
            name='ConnectedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('tv', 'TV'), ('speaker', 'Speaker'), ('light', 'Smart Light'), ('fan', 'Smart Fan'), ('ac', 'Air Conditioner'), ('plug', 'Smart Plug'), ('phone', 'Phone'), ('other', 'Other')], default='other', max_length=30)),
                ('connection_type', models.CharField(choices=[('bluetooth', 'Bluetooth'), ('wifi', 'WiFi'), ('matter', 'Matter'), ('mqtt', 'MQTT')], max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('paired', models.BooleanField(default=False)),
                ('connected', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='homes.home')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='rooms.room')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='DeviceCapability',
        ),
    ]
