# Generated by Django 6.0.6 on 2026-07-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_device_type_remove_device_integration_and_more'),
        ('logs', '0002_alter_devicelog_device'),
        ('scheduler', '0002_alter_schedule_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceState',
        ),
    ]
