# Generated by Django 6.0.6 on 2026-07-03 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_device_type_remove_device_integration_and_more'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.connecteddevice'),
        ),
    ]
