# Generated by Django 6.0.6 on 2026-07-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('connection_type', models.CharField(choices=[('wifi', 'Wi-Fi'), ('bluetooth', 'Bluetooth'), ('mdns', 'mDNS'), ('ssdp', 'SSDP'), ('matter', 'Matter')], max_length=30)),
                ('paired', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
