# Generated by Django 6.0.6 on 2026-07-03 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discovereddevice',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='discovered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discovereddevice',
            name='brand',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='discovereddevice',
            name='device_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='discovereddevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
